export const dataPeople = [
  {
    id: "1",
    name: "Ronal",
    surname: "Varela Jimenez",
    age: 27,
    typeDocument: { code: "cc", name: "Cédula de ciudadanía" },
    identificationNumber: 1082478025,
    sex: "Masculino",
    statusMarital: "Soltero(a)",
    profession: "Ingeniero(a)",
  },
  {
    id: "2",
    name: "Andres",
    surname: "Payares Mejia",
    age: 20,
    typeDocument: { code: "cc", name: "Cédula de ciudadanía" },
    identificationNumber: 1083378025,
    sex: "Masculino",
    statusMarital: "Casado(a)",
    profession: "Arquitecto(a)",
  },
  {
    id: "3",
    name: "Andrea",
    surname: "Garcia",
    age: 24,
    typeDocument: { code: "pasaporte", name: "Pasaporte" },
    identificationNumber: 1100000454,
    sex: "Femenino",
    statusMarital: "Casado(a)",
    profession: "Contador(a)",
  },
  {
    id: "4",
    name: "Valentina",
    surname: "Hernandez parra",
    age: 23,
    typeDocument: { code: "pasaporte", name: "Pasaporte" },
    identificationNumber: 3451111111,
    sex: "Femenino",
    statusMarital: "Soltero(a)",
    profession: "Contador(a)",
  },
];
